### ISSUE TITLE
cluster: Services are not starting after start command

### ISSUE THREAD

**Issue by Nuttymoon** [adaltas/jumbo#10]
Jumbo should start all the cluster's services after the `start` command. It works fine for the first `start` (with the cluster provisioning), but in next cluster start only 3 services are starting: Tez Client, Slider Client and Pig Client...

**Comment by RReivax** [comment]
Start services API is called before Ambari has registered services as `INSTALLED`, therefore ignoring them. 
Log example: 
```
24 Oct 2018 09:37:29,946  INFO [ambari-heartbeat-processor-0] HeartbeatProcessor:607 - State of service component HBASE_MASTER of service HBASE of cluster hbaselocal has changed from UNKNOWN to INSTALLED at host master01.hbase.local according to STATUS_COMMAND report
```
Fix:
Should wait for all services to be `INSTALLED` then run the start API.

**Comment by RReivax** [comment]
Fixed.
