### ISSUE TITLE
storage pool may not exist -- KVM

### ISSUE THREAD

**Issue by busser** [adaltas/jumbo#7]
When using KVM, vagrant fails if storage pool does'nt exists, which is the case by default.
storage pool is configured to "hdp-cluster", but there is no checks for existence, nor auto creation script !!

--> Default conf is not working by default !

**Comment by Nuttymoon** [comment]
Hey there, thanks for trying Jumbo! Indeed, that's something we forgot to automize when open sourcing!  
`hdp-cluster` is not a good name for the storage pool by the way. We will add this to the TODO list.  
What has to be done is write a python script that creates a pool named `jumbo-clusters` if it doesn't exist by leveraging [virsh](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-managing_guest_virtual_machines_with_virsh-storage_pool_commands#sect-Storage_pool_commands-Creating_defining_and_starting_storage_pools) and put it in the `script` section of the [setup.py](https://github.com/adaltas/jumbo/blob/ec419de11785889422fd41dea4b24c0201337fc2/setup.py#L23).

**Comment by Pierrotws** [comment]
With jumbo-clusters default location on ~/.jumbo/storage for example ?

**Comment by Nuttymoon** [comment]
Solved in [v0.4.4](https://github.com/adaltas/jumbo/releases/tag/v0.4.4) (commit: 05765c0f2ddd677715df833ad598f3267d381a1d).  
At installation, a storage pool `jumbo-storage` is created in `/var/lib/libvirt/images/jumbo-storage`.
